[package]
cairo-version = "2.8.4"
name = "ctboc"
version = "1.0.6"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.6" }
starknet = "2.8.4"

[profile.dev]

[profile.staging]